@ File generated by CompCert 3.17
@ Command line: -S -marm -fno-pie -o arm/data.s source/data.c
	.syntax	unified
	.arch	armv7-a
	.fpu	vfpv3-d16
	.eabi_attribute Tag_ABI_VFP_args, 1
	.arm
	.data
	.balign 4
	.globl	shared_value
shared_value:
	.long	20
	.type	shared_value, %object
	.size	shared_value, . - shared_value

	.section .note.GNU-stack,"",%progbits
