# File generated by CompCert 3.17
# Command line: -S -fno-pie -o x86_64/asm_test_entry.s source/asm_test_entry.c
	.text
	.align	16
	.globl asm_test_entry
asm_test_entry:
	.cfi_startproc
	subq	$8, %rsp
	.cfi_adjust_cfa_offset	8
	leaq	16(%rsp), %rax
	movq	%rax, 0(%rsp)
	movl	$42, %eax
	addq	$8, %rsp
	ret
	.cfi_endproc
	.type	asm_test_entry, @function
	.size	asm_test_entry, . - asm_test_entry

	.section .note.GNU-stack,"",%progbits
