# File generated by CompCert 3.17
# Command line: -S -fno-pie -o x86_32/caller.s source/caller.c
	.text
	.align	16
	.globl asm_test_entry
asm_test_entry:
	.cfi_startproc
	subl	$12, %esp
	.cfi_adjust_cfa_offset	12
	leal	16(%esp), %eax
	movl	%eax, 0(%esp)
	movl	shared_value, %eax
	leal	22(%eax), %eax
	movl	%eax, shared_value
	addl	$12, %esp
	ret
	.cfi_endproc
	.type	asm_test_entry, @function
	.size	asm_test_entry, . - asm_test_entry

	.section .note.GNU-stack,"",%progbits
