# File generated by CompCert 3.17
# Command line: -S -fno-pie -o x86_32/cond_select.s source/cond_select.c
	.text
	.align	16
	.globl asm_test_entry
asm_test_entry:
	.cfi_startproc
	subl	$28, %esp
	.cfi_adjust_cfa_offset	28
	leal	32(%esp), %eax
	movl	%eax, 0(%esp)
	movl	%ebx, 4(%esp)
	movl	$20, %eax
	movl	%eax, 8(%esp)
	movl	$22, %eax
	movl	%eax, 12(%esp)
	movl	8(%esp), %ecx
	movl	12(%esp), %edx
	cmpl	%edx, %ecx
	jl	.L100
	movl	8(%esp), %edx
	jmp	.L101
.L100:
	movl	12(%esp), %edx
.L101:
	movl	8(%esp), %ecx
	movl	12(%esp), %eax
	cmpl	%eax, %ecx
	jg	.L102
	movl	12(%esp), %ecx
	jmp	.L103
.L102:
	movl	8(%esp), %ecx
.L103:
	leal	20(%edx), %eax
	xorl	%ebx, %ebx
	cmpl	%ecx, %edx
	cmovne	%ebx, %eax
	movl	4(%esp), %ebx
	addl	$28, %esp
	ret
	.cfi_endproc
	.type	asm_test_entry, @function
	.size	asm_test_entry, . - asm_test_entry

	.section .note.GNU-stack,"",%progbits
