# File generated by CompCert 3.17
# Command line: -S -fno-pie -o riscv64/data.s source/data.c
	.option nopic
	.data
	.balign 4
	.globl	shared_value
shared_value:
	.long	20
	.type	shared_value, @object
	.size	shared_value, . - shared_value

	.section .note.GNU-stack,"",%progbits
