# File generated by CompCert 3.17
# Command line: -S -o riscv64/args_arith.s source/args_arith.c
	.option pic
	.text
	.balign 2
	.globl asm_test_sum
asm_test_sum:
	.cfi_startproc
	mv	x30, x2
	addi	x2, x2, -16
	.cfi_adjust_cfa_offset	16
	sd	x30, 0(x2)
	sd	x1, 8(x2)
	.cfi_rel_offset	x1, 8
	mulw	x11, x11, x12
	addw	x12, x10, x11
	subw	x10, x12, x13
	ld	x1, 8(x2)
	addi	x2, x2, 16
	jr	x1
	.cfi_endproc
	.type	asm_test_sum, @function
	.size	asm_test_sum, . - asm_test_sum
	.text
	.balign 2
	.globl asm_test_entry
asm_test_entry:
	.cfi_startproc
	mv	x30, x2
	addi	x2, x2, -32
	.cfi_adjust_cfa_offset	32
	sd	x30, 0(x2)
	sd	x1, 8(x2)
	.cfi_rel_offset	x1, 8
	addiw	x6, x0, 7
	sw	x6, 20(x2)
	addiw	x6, x0, 5
	sw	x6, 24(x2)
	addiw	x6, x0, 9
	sw	x6, 16(x2)
	lw	x15, 20(x2)
	lw	x10, 24(x2)
	mulw	x14, x15, x10
	lw	x13, 16(x2)
	subw	x12, x14, x13
	lw	x11, 24(x2)
	slliw	x10, x11, 1
	addw	x6, x12, x10
	addiw	x10, x6, 6
	ld	x1, 8(x2)
	addi	x2, x2, 32
	jr	x1
	.cfi_endproc
	.type	asm_test_entry, @function
	.size	asm_test_entry, . - asm_test_entry

	.section .note.GNU-stack,"",%progbits
