@ File generated by CompCert 3.17
@ Command line: -S -marm -o arm/loop.s source/loop.c
	.syntax	unified
	.arch	armv7-a
	.fpu	vfpv3-d16
	.eabi_attribute Tag_ABI_VFP_args, 1
	.arm
	.text
	.balign 4
	.globl asm_test_entry
asm_test_entry:
	.cfi_startproc
	mov	r12, sp
	sub	sp, sp, #16
	.cfi_adjust_cfa_offset	16
	str	r12, [sp, #0]
	str	lr, [sp, #4]
	.cfi_rel_offset	lr, 4
	mov	r0, #6
	str	r0, [sp, #8]
	mov	r0, #0
	mov	r2, #0
.L100:
	ldr	r1, [sp, #8]
	cmp	r2, r1
	bge	.L101
	add	r0, r0, #7
	add	r2, r2, #1
	b	.L100
.L101:
	ldr	lr, [sp, #4]
	add	sp, sp, #16
	bx	lr
	.cfi_endproc
	.type	asm_test_entry, %function
	.size	asm_test_entry, . - asm_test_entry

	.section .note.GNU-stack,"",%progbits
