# File generated by CompCert 3.17
# Command line: -S -o x86_64/global_ldst.s source/global_ldst.c
	.data
	.align	4
	.globl	asm_test_global
asm_test_global:
	.long	20
	.type	asm_test_global, @object
	.size	asm_test_global, . - asm_test_global
	.text
	.align	16
	.globl asm_test_entry
asm_test_entry:
	.cfi_startproc
	subq	$8, %rsp
	.cfi_adjust_cfa_offset	8
	leaq	16(%rsp), %rax
	movq	%rax, 0(%rsp)
	movl	asm_test_global(%rip), %eax
	leal	22(%eax), %eax
	movl	%eax, asm_test_global(%rip)
	addq	$8, %rsp
	ret
	.cfi_endproc
	.type	asm_test_entry, @function
	.size	asm_test_entry, . - asm_test_entry

	.section .note.GNU-stack,"",%progbits
