# File generated by CompCert 3.17
# Command line: -S -o x86_64/loop.s source/loop.c
	.text
	.align	16
	.globl asm_test_entry
asm_test_entry:
	.cfi_startproc
	subq	$24, %rsp
	.cfi_adjust_cfa_offset	24
	leaq	32(%rsp), %rax
	movq	%rax, 0(%rsp)
	movl	$6, %eax
	movl	%eax, 8(%rsp)
	xorl	%eax, %eax
	xorl	%edx, %edx
.L100:
	movl	8(%rsp), %ecx
	cmpl	%ecx, %edx
	jge	.L101
	leal	7(%eax), %eax
	leal	1(%edx), %edx
	jmp	.L100
.L101:
	addq	$24, %rsp
	ret
	.cfi_endproc
	.type	asm_test_entry, @function
	.size	asm_test_entry, . - asm_test_entry

	.section .note.GNU-stack,"",%progbits
