@ File generated by CompCert 3.17
@ Command line: -S -marm -o arm/global_ldst.s source/global_ldst.c
	.syntax	unified
	.arch	armv7-a
	.fpu	vfpv3-d16
	.eabi_attribute Tag_ABI_VFP_args, 1
	.arm
	.data
	.balign 4
	.globl	asm_test_global
asm_test_global:
	.long	20
	.type	asm_test_global, %object
	.size	asm_test_global, . - asm_test_global
	.text
	.balign 4
	.globl asm_test_entry
asm_test_entry:
	.cfi_startproc
	mov	r12, sp
	sub	sp, sp, #8
	.cfi_adjust_cfa_offset	8
	str	r12, [sp, #0]
	str	lr, [sp, #4]
	.cfi_rel_offset	lr, 4
	movw	r1, #:lower16:asm_test_global
	movt	r1, #:upper16:asm_test_global
	ldr	r2, [r1, #0]
	add	r0, r2, #22
	str	r0, [r1, #0]
	ldr	lr, [sp, #4]
	add	sp, sp, #8
	bx	lr
	.cfi_endproc
	.type	asm_test_entry, %function
	.size	asm_test_entry, . - asm_test_entry

	.section .note.GNU-stack,"",%progbits
