# File generated by CompCert 3.17
# Command line: -S -fno-pie -o x86_32/i64_divmod.s source/i64_divmod.c
	.data
	.align	8
	.globl	i64_divmod_dividend
i64_divmod_dividend:
	.long	0x5ec47a00, 0xfffffffe
	.type	i64_divmod_dividend, @object
	.size	i64_divmod_dividend, . - i64_divmod_dividend
	.data
	.align	8
	.globl	i64_divmod_divisor
i64_divmod_divisor:
	.long	0xd, 0x0
	.type	i64_divmod_divisor, @object
	.size	i64_divmod_divisor, . - i64_divmod_divisor
	.data
	.align	8
	.globl	i64_divmod_quotient
i64_divmod_quotient:
	.long	0xffffffff, 0xffffffff
	.type	i64_divmod_quotient, @object
	.size	i64_divmod_quotient, . - i64_divmod_quotient
	.data
	.align	8
	.globl	i64_divmod_remainder
i64_divmod_remainder:
	.long	0xffffffff, 0xffffffff
	.type	i64_divmod_remainder, @object
	.size	i64_divmod_remainder, . - i64_divmod_remainder
	.text
	.align	16
	.globl asm_test_entry
asm_test_entry:
	.cfi_startproc
	subl	$44, %esp
	.cfi_adjust_cfa_offset	44
	leal	48(%esp), %eax
	movl	%eax, 16(%esp)
	movl	%ebx, 20(%esp)
	movl	%esi, 24(%esp)
	movl	i64_divmod_dividend, %eax
	movl	(i64_divmod_dividend + 4), %ecx
	movl	i64_divmod_divisor, %ebx
	movl	(i64_divmod_divisor + 4), %esi
	movl	%esi, 12(%esp)
	movl	%ebx, 8(%esp)
	movl	%ecx, 4(%esp)
	movl	%eax, 0(%esp)
	call	__compcert_i64_sdiv
	movl	%eax, i64_divmod_quotient
	movl	%edx, (i64_divmod_quotient + 4)
	movl	i64_divmod_dividend, %ebx
	movl	(i64_divmod_dividend + 4), %esi
	movl	i64_divmod_divisor, %eax
	movl	(i64_divmod_divisor + 4), %ecx
	movl	%ecx, 12(%esp)
	movl	%eax, 8(%esp)
	movl	%esi, 4(%esp)
	movl	%ebx, 0(%esp)
	call	__compcert_i64_smod
	movl	%eax, i64_divmod_remainder
	movl	%edx, (i64_divmod_remainder + 4)
	movl	$42, %eax
	movl	20(%esp), %ebx
	movl	24(%esp), %esi
	addl	$44, %esp
	ret
	.cfi_endproc
	.type	asm_test_entry, @function
	.size	asm_test_entry, . - asm_test_entry

	.section .note.GNU-stack,"",%progbits
