// File generated by CompCert 3.17
// Command line: -S -fno-pie -o aarch64/args_arith.s source/args_arith.c
	.text
	.balign 4
	.globl asm_test_sum
asm_test_sum:
	.cfi_startproc
	mov	x15, sp
	stp	x15, x30, [sp, #-16]!
	.cfi_adjust_cfa_offset	16
	.cfi_rel_offset	x30, 8
	madd	w1, w1, w2, w0
	sub	w0, w1, w3
	ldr	x30, [sp, #8]
	add	sp, sp, #16
	ret	x30
	.cfi_endproc
	.type	asm_test_sum, @function
	.size	asm_test_sum, . - asm_test_sum
	.text
	.balign 4
	.globl asm_test_entry
asm_test_entry:
	.cfi_startproc
	mov	x15, sp
	stp	x15, x30, [sp, #-32]!
	.cfi_adjust_cfa_offset	32
	.cfi_rel_offset	x30, 8
	orr	w0, wzr, #7
	str	w0, [sp, #20]
	movz	w0, #5, lsl #0
	str	w0, [sp, #24]
	movz	w0, #9, lsl #0
	str	w0, [sp, #16]
	ldr	w3, [sp, #20]
	ldr	w4, [sp, #24]
	madd	w2, w3, w4, wzr
	ldr	w5, [sp, #16]
	sub	w0, w2, w5
	ldr	w1, [sp, #24]
	add	w0, w0, w1, lsl #1
	add	w0, w0, #6
	ldr	x30, [sp, #8]
	add	sp, sp, #32
	ret	x30
	.cfi_endproc
	.type	asm_test_entry, @function
	.size	asm_test_entry, . - asm_test_entry

	.section .note.GNU-stack,"",%progbits
