// File generated by CompCert 3.17
// Command line: -S -fno-pie -o aarch64/global_ldst.s source/global_ldst.c
	.data
	.balign 4
	.globl	asm_test_global
asm_test_global:
	.long	20
	.type	asm_test_global, @object
	.size	asm_test_global, . - asm_test_global
	.text
	.balign 4
	.globl asm_test_entry
asm_test_entry:
	.cfi_startproc
	mov	x15, sp
	stp	x15, x30, [sp, #-16]!
	.cfi_adjust_cfa_offset	16
	.cfi_rel_offset	x30, 8
	adrp	x16, asm_test_global
	ldr	w0, [x16, #:lo12:asm_test_global]
	add	w0, w0, #22
	adrp	x16, asm_test_global
	str	w0, [x16, #:lo12:asm_test_global]
	ldr	x30, [sp, #8]
	add	sp, sp, #16
	ret	x30
	.cfi_endproc
	.type	asm_test_entry, @function
	.size	asm_test_entry, . - asm_test_entry

	.section .note.GNU-stack,"",%progbits
