@ File generated by CompCert 3.17
@ Command line: -S -marm -fno-pie -o arm/args_arith.s source/args_arith.c
	.syntax	unified
	.arch	armv7-a
	.fpu	vfpv3-d16
	.eabi_attribute Tag_ABI_VFP_args, 1
	.arm
	.text
	.balign 4
	.globl asm_test_sum
asm_test_sum:
	.cfi_startproc
	mov	r12, sp
	sub	sp, sp, #8
	.cfi_adjust_cfa_offset	8
	str	r12, [sp, #0]
	str	lr, [sp, #4]
	.cfi_rel_offset	lr, 4
	mla	r1, r1, r2, r0
	sub	r0, r1, r3
	ldr	lr, [sp, #4]
	add	sp, sp, #8
	bx	lr
	.cfi_endproc
	.type	asm_test_sum, %function
	.size	asm_test_sum, . - asm_test_sum
	.text
	.balign 4
	.globl asm_test_entry
asm_test_entry:
	.cfi_startproc
	mov	r12, sp
	sub	sp, sp, #24
	.cfi_adjust_cfa_offset	24
	str	r12, [sp, #0]
	str	lr, [sp, #4]
	.cfi_rel_offset	lr, 4
	mov	r0, #7
	str	r0, [sp, #12]
	mov	r0, #5
	str	r0, [sp, #16]
	mov	r0, #9
	str	r0, [sp, #8]
	ldr	r3, [sp, #12]
	ldr	r12, [sp, #16]
	mul	r2, r3, r12
	ldr	r0, [sp, #8]
	sub	r0, r2, r0
	ldr	r1, [sp, #16]
	add	r0, r0, r1, lsl #1
	add	r0, r0, #6
	ldr	lr, [sp, #4]
	add	sp, sp, #24
	bx	lr
	.cfi_endproc
	.type	asm_test_entry, %function
	.size	asm_test_entry, . - asm_test_entry

	.section .note.GNU-stack,"",%progbits
