# File generated by CompCert 3.17
# Command line: -S -fno-pie -o x86_64/data.s source/data.c
	.data
	.align	4
	.globl	shared_value
shared_value:
	.long	20
	.type	shared_value, @object
	.size	shared_value, . - shared_value

	.section .note.GNU-stack,"",%progbits
