@ File generated by CompCert 3.17
@ Command line: -S -marm -fno-pie -o arm/direct_call.s source/direct_call.c
	.syntax	unified
	.arch	armv7-a
	.fpu	vfpv3-d16
	.eabi_attribute Tag_ABI_VFP_args, 1
	.arm
	.text
	.balign 4
	.globl asm_test_callee
asm_test_callee:
	.cfi_startproc
	mov	r12, sp
	sub	sp, sp, #8
	.cfi_adjust_cfa_offset	8
	str	r12, [sp, #0]
	str	lr, [sp, #4]
	.cfi_rel_offset	lr, 4
	add	r0, r0, r0
	ldr	lr, [sp, #4]
	add	sp, sp, #8
	bx	lr
	.cfi_endproc
	.type	asm_test_callee, %function
	.size	asm_test_callee, . - asm_test_callee
	.text
	.balign 4
	.globl asm_test_entry
asm_test_entry:
	.cfi_startproc
	mov	r12, sp
	sub	sp, sp, #8
	.cfi_adjust_cfa_offset	8
	str	r12, [sp, #0]
	str	lr, [sp, #4]
	.cfi_rel_offset	lr, 4
	mov	r0, #20
	bl	asm_test_callee
	add	r0, r0, #2
	ldr	lr, [sp, #4]
	add	sp, sp, #8
	bx	lr
	.cfi_endproc
	.type	asm_test_entry, %function
	.size	asm_test_entry, . - asm_test_entry

	.section .note.GNU-stack,"",%progbits
