// File generated by CompCert 3.17
// Command line: -S -o aarch64/asm_test_entry.s source/asm_test_entry.c
	.text
	.balign 4
	.globl asm_test_entry
asm_test_entry:
	.cfi_startproc
	mov	x15, sp
	stp	x15, x30, [sp, #-16]!
	.cfi_adjust_cfa_offset	16
	.cfi_rel_offset	x30, 8
	movz	w0, #42, lsl #0
	ldr	x30, [sp, #8]
	add	sp, sp, #16
	ret	x30
	.cfi_endproc
	.type	asm_test_entry, @function
	.size	asm_test_entry, . - asm_test_entry

	.section .note.GNU-stack,"",%progbits
