#!/usr/bin/env bash
# Write embed_config_data.ml (the table Embed_config serves configuration keys
# from) to stdout, from a target's compcert.ini.
#
# Values are split into words on whitespace, as Readconfig does. Readconfig
# also understands shell-style quoting and backslash continuations; configure
# never emits those, so rather than reimplement them this generator refuses
# any line that uses them, and the sync fails instead of drifting.
set -euo pipefail

ini="${1:?usage: $0 <compcert.ini>}"
[ -f "$ini" ] || { echo "FATAL: missing $ini" >&2; exit 1; }

if grep -n "[\"'\\\\]" "$ini" >&2; then
  echo "FATAL: $ini uses quoting or escapes, which this generator does not support" >&2
  exit 1
fi

echo "(* Generated by gen-config-data.sh from compcert.ini. Do not edit. *)"
echo
echo "let table : (string * string list) list ="
echo "  ["
awk '
  /^[[:space:]]*(#|$)/ { next }
  {
    eq = index($0, "=")
    if (eq == 0) { print "FATAL: line " NR " has no =" > "/dev/stderr"; exit 1 }
    key = substr($0, 1, eq - 1)
    gsub(/^[[:space:]]+|[[:space:]]+$/, "", key)
    n = split(substr($0, eq + 1), words, /[[:space:]]+/)
    line = "    (\"" key "\", ["
    sep = ""
    for (i = 1; i <= n; i++) {
      if (words[i] == "") continue
      line = line sep "\"" words[i] "\""
      sep = "; "
    }
    print line "]);"
  }
' "$ini"
echo "  ]"
