#!/usr/bin/env bash
# Write embed_config_data.ml (the table Embed_config serves configuration keys
# from) to stdout, from a target's compcert.ini.
#
# The file is read by CompCert's own Readconfig (the synced Readconfig.ml,
# given as the second argument), not by a reimplementation, so shell-style
# quoting and backslash continuations - which configure does emit, e.g. arm's
# quoted prepro_options - split into words exactly as ccomp would split them.
set -euo pipefail

ini="${1:?usage: $0 <compcert.ini> <Readconfig.ml>}"
readconfig="${2:?usage: $0 <compcert.ini> <Readconfig.ml>}"
[ -f "$ini" ] || { echo "FATAL: missing $ini" >&2; exit 1; }
[ -f "$readconfig" ] || { echo "FATAL: missing $readconfig" >&2; exit 1; }

Opam() { if command -v opam >/dev/null 2>&1; then opam exec -- "$@"; else "$@"; fi; }

script=$(mktemp --suffix=.ml)
trap 'rm -f "$script"' EXIT
# Readconfig.ml without its .mli, so its table can be listed; then the dump.
# Keys are sorted, and each is looked up with Readconfig's own [key_val], so
# a repeated key keeps the value ccomp would see.
{
  cat "$readconfig"
  cat <<'OCAML'
let () =
  read_config_file Sys.argv.(1);
  let keys = Hashtbl.fold (fun k _ acc -> k :: acc) key_val_tbl [] |> List.sort_uniq compare in
  print_string "(* Generated by gen-config-data.sh from compcert.ini. Do not edit. *)\n\n";
  print_string "let table : (string * string list) list =\n  [\n";
  List.iter
    (fun k ->
      let v = Option.get (key_val k) in
      Printf.printf "    (%S, [%s]);\n" k (String.concat "; " (List.map (Printf.sprintf "%S") v)))
    keys;
  print_string "  ]\n"
OCAML
} > "$script"
Opam ocaml "$script" "$ini"
