# File generated by CompCert 3.17
# Command line: -S -fno-pie -o x86_32/args_arith.s source/args_arith.c
	.text
	.align	16
	.globl asm_test_sum
asm_test_sum:
	.cfi_startproc
	subl	$28, %esp
	.cfi_adjust_cfa_offset	28
	leal	32(%esp), %eax
	movl	%eax, 0(%esp)
	movl	%ebx, 4(%esp)
	movl	%esi, 8(%esp)
	movl	%edi, 12(%esp)
	movl	12(%eax), %ebx
	movl	8(%eax), %esi
	movl	4(%eax), %ecx
	movl	0(%eax), %edi
	imull	%esi, %ecx
	leal	0(%edi,%ecx,1), %eax
	subl	%ebx, %eax
	movl	4(%esp), %ebx
	movl	8(%esp), %esi
	movl	12(%esp), %edi
	addl	$28, %esp
	ret
	.cfi_endproc
	.type	asm_test_sum, @function
	.size	asm_test_sum, . - asm_test_sum
	.text
	.align	16
	.globl asm_test_entry
asm_test_entry:
	.cfi_startproc
	subl	$28, %esp
	.cfi_adjust_cfa_offset	28
	leal	32(%esp), %eax
	movl	%eax, 0(%esp)
	movl	$7, %eax
	movl	%eax, 12(%esp)
	movl	$5, %eax
	movl	%eax, 16(%esp)
	movl	$9, %eax
	movl	%eax, 8(%esp)
	movl	12(%esp), %eax
	movl	16(%esp), %ecx
	imull	%ecx, %eax
	movl	8(%esp), %ecx
	subl	%ecx, %eax
	movl	16(%esp), %edx
	leal	6(%eax,%edx,2), %eax
	addl	$28, %esp
	ret
	.cfi_endproc
	.type	asm_test_entry, @function
	.size	asm_test_entry, . - asm_test_entry

	.section .note.GNU-stack,"",%progbits
