# File generated by CompCert 3.17
# Command line: -S -fno-pie -o x86_64/callee.s source/callee.c
	.text
	.align	16
	.globl asm_test_callee
asm_test_callee:
	.cfi_startproc
	subq	$8, %rsp
	.cfi_adjust_cfa_offset	8
	leaq	16(%rsp), %rax
	movq	%rax, 0(%rsp)
	leal	0(%edi,%edi,1), %eax
	addq	$8, %rsp
	ret
	.cfi_endproc
	.type	asm_test_callee, @function
	.size	asm_test_callee, . - asm_test_callee

	.section .note.GNU-stack,"",%progbits
