# File generated by CompCert 3.17
# Command line: -S -fno-pie -o riscv32/args_arith.s source/args_arith.c
	.option nopic
	.text
	.balign 2
	.globl asm_test_sum
asm_test_sum:
	.cfi_startproc
	mv	x30, x2
	addi	x2, x2, -16
	.cfi_adjust_cfa_offset	16
	sw	x30, 0(x2)
	sw	x1, 4(x2)
	.cfi_rel_offset	x1, 4
	mul	x11, x11, x12
	add	x12, x10, x11
	sub	x10, x12, x13
	lw	x1, 4(x2)
	addi	x2, x2, 16
	jr	x1
	.cfi_endproc
	.type	asm_test_sum, @function
	.size	asm_test_sum, . - asm_test_sum
	.text
	.balign 2
	.globl asm_test_entry
asm_test_entry:
	.cfi_startproc
	mv	x30, x2
	addi	x2, x2, -32
	.cfi_adjust_cfa_offset	32
	sw	x30, 0(x2)
	sw	x1, 4(x2)
	.cfi_rel_offset	x1, 4
	addi	x6, x0, 7
	sw	x6, 12(x2)
	addi	x6, x0, 5
	sw	x6, 16(x2)
	addi	x6, x0, 9
	sw	x6, 8(x2)
	lw	x15, 12(x2)
	lw	x10, 16(x2)
	mul	x14, x15, x10
	lw	x13, 8(x2)
	sub	x12, x14, x13
	lw	x11, 16(x2)
	slli	x10, x11, 1
	add	x6, x12, x10
	addi	x10, x6, 6
	lw	x1, 4(x2)
	addi	x2, x2, 32
	jr	x1
	.cfi_endproc
	.type	asm_test_entry, @function
	.size	asm_test_entry, . - asm_test_entry

	.section .note.GNU-stack,"",%progbits
