@ File generated by CompCert 3.17
@ Command line: -S -marm -fno-pie -o arm/data.s source/data.c
	.syntax	unified
	.arch	armv7-a
	.fpu	vfpv3-d16
	.eabi_attribute Tag_ABI_VFP_args, 1
	.arm
	.comm	shared_value, 4, 4

	.section .note.GNU-stack,"",%progbits
