# File generated by CompCert 3.17
# Command line: -S -fno-pie -o x86_32/callee.s source/callee.c
	.text
	.align	16
	.globl asm_test_callee
asm_test_callee:
	.cfi_startproc
	subl	$12, %esp
	.cfi_adjust_cfa_offset	12
	leal	16(%esp), %eax
	movl	%eax, 0(%esp)
	movl	0(%eax), %ecx
	leal	0(%ecx,%ecx,1), %eax
	addl	$12, %esp
	ret
	.cfi_endproc
	.type	asm_test_callee, @function
	.size	asm_test_callee, . - asm_test_callee

	.section .note.GNU-stack,"",%progbits
