# File generated by CompCert 3.17
# Command line: -S -o riscv64/loop.s source/loop.c
	.option pic
	.text
	.balign 2
	.globl asm_test_entry
asm_test_entry:
	.cfi_startproc
	mv	x30, x2
	addi	x2, x2, -32
	.cfi_adjust_cfa_offset	32
	sd	x30, 0(x2)
	sd	x1, 8(x2)
	.cfi_rel_offset	x1, 8
	addiw	x6, x0, 6
	sw	x6, 16(x2)
	addiw	x10, x0, 0
	addiw	x12, x0, 0
.L100:
	lw	x11, 16(x2)
	bge	x12, x11, .L101
	addiw	x10, x10, 7
	addiw	x12, x12, 1
	j	.L100
.L101:
	ld	x1, 8(x2)
	addi	x2, x2, 32
	jr	x1
	.cfi_endproc
	.type	asm_test_entry, @function
	.size	asm_test_entry, . - asm_test_entry

	.section .note.GNU-stack,"",%progbits
