# File generated by CompCert 3.17
# Command line: -S -fno-pie -o riscv32/cond_select.s source/cond_select.c
	.option nopic
	.text
	.balign 2
	.globl asm_test_entry
asm_test_entry:
	.cfi_startproc
	mv	x30, x2
	addi	x2, x2, -16
	.cfi_adjust_cfa_offset	16
	sw	x30, 0(x2)
	sw	x1, 4(x2)
	.cfi_rel_offset	x1, 4
	addi	x6, x0, 20
	sw	x6, 8(x2)
	addi	x6, x0, 22
	sw	x6, 12(x2)
	lw	x14, 8(x2)
	lw	x12, 12(x2)
	blt	x14, x12, .L100
	lw	x11, 8(x2)
	j	.L101
.L100:
	lw	x11, 12(x2)
.L101:
	lw	x15, 8(x2)
	lw	x13, 12(x2)
	blt	x13, x15, .L102
	lw	x10, 12(x2)
	j	.L103
.L102:
	lw	x10, 8(x2)
.L103:
	beq	x11, x10, .L104
	addi	x10, x0, 0
	j	.L105
.L104:
	addi	x10, x11, 20
.L105:
	lw	x1, 4(x2)
	addi	x2, x2, 16
	jr	x1
	.cfi_endproc
	.type	asm_test_entry, @function
	.size	asm_test_entry, . - asm_test_entry

	.section .note.GNU-stack,"",%progbits
