// File generated by CompCert 3.17
// Command line: -S -o aarch64/cond_select.s source/cond_select.c
	.text
	.balign 4
	.globl asm_test_entry
asm_test_entry:
	.cfi_startproc
	mov	x15, sp
	stp	x15, x30, [sp, #-32]!
	.cfi_adjust_cfa_offset	32
	.cfi_rel_offset	x30, 8
	movz	w0, #20, lsl #0
	str	w0, [sp, #16]
	movz	w0, #22, lsl #0
	str	w0, [sp, #20]
	ldr	w4, [sp, #16]
	ldr	w2, [sp, #20]
	cmp	w4, w2
	b.lt	.L100
	ldr	w1, [sp, #16]
	b	.L101
.L100:
	ldr	w1, [sp, #20]
.L101:
	ldr	w7, [sp, #16]
	ldr	w3, [sp, #20]
	cmp	w7, w3
	b.gt	.L102
	ldr	w0, [sp, #20]
	b	.L103
.L102:
	ldr	w0, [sp, #16]
.L103:
	add	w5, w1, #20
	movz	w6, #0, lsl #0
	cmp	w1, w0
	csel	x0, x5, x6, eq
	ldr	x30, [sp, #8]
	add	sp, sp, #32
	ret	x30
	.cfi_endproc
	.type	asm_test_entry, @function
	.size	asm_test_entry, . - asm_test_entry

	.section .note.GNU-stack,"",%progbits
