// File generated by CompCert 3.17
// Command line: -S -fno-pie -o aarch64/loop.s source/loop.c
	.text
	.balign 4
	.globl asm_test_entry
asm_test_entry:
	.cfi_startproc
	mov	x15, sp
	stp	x15, x30, [sp, #-32]!
	.cfi_adjust_cfa_offset	32
	.cfi_rel_offset	x30, 8
	orr	w0, wzr, #6
	str	w0, [sp, #16]
	movz	w0, #0, lsl #0
	movz	w2, #0, lsl #0
.L100:
	ldr	w1, [sp, #16]
	cmp	w2, w1
	b.ge	.L101
	add	w0, w0, #7
	add	w2, w2, #1
	b	.L100
.L101:
	ldr	x30, [sp, #8]
	add	sp, sp, #32
	ret	x30
	.cfi_endproc
	.type	asm_test_entry, @function
	.size	asm_test_entry, . - asm_test_entry

	.section .note.GNU-stack,"",%progbits
