# File generated by CompCert 3.17
# Command line: -S -o riscv32/global_ldst.s source/global_ldst.c
	.option pic
	.data
	.balign 4
	.globl	asm_test_global
asm_test_global:
	.long	20
	.type	asm_test_global, @object
	.size	asm_test_global, . - asm_test_global
	.text
	.balign 2
	.globl asm_test_entry
asm_test_entry:
	.cfi_startproc
	mv	x30, x2
	addi	x2, x2, -16
	.cfi_adjust_cfa_offset	16
	sw	x30, 0(x2)
	sw	x1, 4(x2)
	.cfi_rel_offset	x1, 4
1:	auipc	x31, %pcrel_hi(asm_test_global)
	lw	x6, %pcrel_lo(1b)(x31)
	addi	x10, x6, 22
1:	auipc	x31, %pcrel_hi(asm_test_global)
	sw	x10, %pcrel_lo(1b)(x31)
	lw	x1, 4(x2)
	addi	x2, x2, 16
	jr	x1
	.cfi_endproc
	.type	asm_test_entry, @function
	.size	asm_test_entry, . - asm_test_entry

	.section .note.GNU-stack,"",%progbits
