# File generated by CompCert 3.17
# Command line: -S -fno-pie -o x86_64/args_arith.s source/args_arith.c
	.text
	.align	16
	.globl asm_test_sum
asm_test_sum:
	.cfi_startproc
	subq	$8, %rsp
	.cfi_adjust_cfa_offset	8
	leaq	16(%rsp), %rax
	movq	%rax, 0(%rsp)
	imull	%edx, %esi
	leal	0(%edi,%esi,1), %eax
	subl	%ecx, %eax
	addq	$8, %rsp
	ret
	.cfi_endproc
	.type	asm_test_sum, @function
	.size	asm_test_sum, . - asm_test_sum
	.text
	.align	16
	.globl asm_test_entry
asm_test_entry:
	.cfi_startproc
	subq	$24, %rsp
	.cfi_adjust_cfa_offset	24
	leaq	32(%rsp), %rax
	movq	%rax, 0(%rsp)
	movl	$7, %eax
	movl	%eax, 12(%rsp)
	movl	$5, %eax
	movl	%eax, 16(%rsp)
	movl	$9, %eax
	movl	%eax, 8(%rsp)
	movl	12(%rsp), %eax
	movl	16(%rsp), %esi
	imull	%esi, %eax
	movl	8(%rsp), %ecx
	subl	%ecx, %eax
	movl	16(%rsp), %edx
	leal	6(%eax,%edx,2), %eax
	addq	$24, %rsp
	ret
	.cfi_endproc
	.type	asm_test_entry, @function
	.size	asm_test_entry, . - asm_test_entry

	.section .note.GNU-stack,"",%progbits
