# File generated by CompCert 3.17
# Command line: -S -o riscv32/loop.s source/loop.c
	.option pic
	.text
	.balign 2
	.globl asm_test_entry
asm_test_entry:
	.cfi_startproc
	mv	x30, x2
	addi	x2, x2, -16
	.cfi_adjust_cfa_offset	16
	sw	x30, 0(x2)
	sw	x1, 4(x2)
	.cfi_rel_offset	x1, 4
	addi	x6, x0, 6
	sw	x6, 8(x2)
	addi	x10, x0, 0
	addi	x12, x0, 0
.L100:
	lw	x11, 8(x2)
	bge	x12, x11, .L101
	addi	x10, x10, 7
	addi	x12, x12, 1
	j	.L100
.L101:
	lw	x1, 4(x2)
	addi	x2, x2, 16
	jr	x1
	.cfi_endproc
	.type	asm_test_entry, @function
	.size	asm_test_entry, . - asm_test_entry

	.section .note.GNU-stack,"",%progbits
