# File generated by CompCert 3.17
# Command line: -S -fno-pie -o riscv32/callee.s source/callee.c
	.option nopic
	.text
	.balign 2
	.globl asm_test_callee
asm_test_callee:
	.cfi_startproc
	mv	x30, x2
	addi	x2, x2, -16
	.cfi_adjust_cfa_offset	16
	sw	x30, 0(x2)
	sw	x1, 4(x2)
	.cfi_rel_offset	x1, 4
	add	x10, x10, x10
	lw	x1, 4(x2)
	addi	x2, x2, 16
	jr	x1
	.cfi_endproc
	.type	asm_test_callee, @function
	.size	asm_test_callee, . - asm_test_callee

	.section .note.GNU-stack,"",%progbits
