# File generated by CompCert 3.17
# Command line: -S -o riscv32/asm_test_entry.s source/asm_test_entry.c
	.option pic
	.text
	.balign 2
	.globl asm_test_entry
asm_test_entry:
	.cfi_startproc
	mv	x30, x2
	addi	x2, x2, -16
	.cfi_adjust_cfa_offset	16
	sw	x30, 0(x2)
	sw	x1, 4(x2)
	.cfi_rel_offset	x1, 4
	addi	x10, x0, 42
	lw	x1, 4(x2)
	addi	x2, x2, 16
	jr	x1
	.cfi_endproc
	.type	asm_test_entry, @function
	.size	asm_test_entry, . - asm_test_entry

	.section .note.GNU-stack,"",%progbits
