# File generated by CompCert 3.17
# Command line: -S -o riscv64/cond_select.s source/cond_select.c
	.option pic
	.text
	.balign 2
	.globl asm_test_entry
asm_test_entry:
	.cfi_startproc
	mv	x30, x2
	addi	x2, x2, -32
	.cfi_adjust_cfa_offset	32
	sd	x30, 0(x2)
	sd	x1, 8(x2)
	.cfi_rel_offset	x1, 8
	addiw	x6, x0, 20
	sw	x6, 16(x2)
	addiw	x6, x0, 22
	sw	x6, 20(x2)
	lw	x14, 16(x2)
	lw	x12, 20(x2)
	blt	x14, x12, .L100
	lw	x11, 16(x2)
	j	.L101
.L100:
	lw	x11, 20(x2)
.L101:
	lw	x15, 16(x2)
	lw	x13, 20(x2)
	blt	x13, x15, .L102
	lw	x10, 20(x2)
	j	.L103
.L102:
	lw	x10, 16(x2)
.L103:
	beq	x11, x10, .L104
	addiw	x10, x0, 0
	j	.L105
.L104:
	addiw	x10, x11, 20
.L105:
	ld	x1, 8(x2)
	addi	x2, x2, 32
	jr	x1
	.cfi_endproc
	.type	asm_test_entry, @function
	.size	asm_test_entry, . - asm_test_entry

	.section .note.GNU-stack,"",%progbits
