// File generated by CompCert 3.17
// Command line: -S -fno-pie -o aarch64/callee.s source/callee.c
	.text
	.balign 4
	.globl asm_test_callee
asm_test_callee:
	.cfi_startproc
	mov	x15, sp
	stp	x15, x30, [sp, #-16]!
	.cfi_adjust_cfa_offset	16
	.cfi_rel_offset	x30, 8
	add	w0, w0, w0
	ldr	x30, [sp, #8]
	add	sp, sp, #16
	ret	x30
	.cfi_endproc
	.type	asm_test_callee, @function
	.size	asm_test_callee, . - asm_test_callee

	.section .note.GNU-stack,"",%progbits
