@ File generated by CompCert 3.17
@ Command line: -S -marm -o arm/cond_select.s source/cond_select.c
	.syntax	unified
	.arch	armv7-a
	.fpu	vfpv3-d16
	.eabi_attribute Tag_ABI_VFP_args, 1
	.arm
	.text
	.balign 4
	.globl asm_test_entry
asm_test_entry:
	.cfi_startproc
	mov	r12, sp
	sub	sp, sp, #16
	.cfi_adjust_cfa_offset	16
	str	r12, [sp, #0]
	str	lr, [sp, #4]
	.cfi_rel_offset	lr, 4
	mov	r0, #20
	str	r0, [sp, #8]
	mov	r0, #22
	str	r0, [sp, #12]
	ldr	r12, [sp, #8]
	ldr	r2, [sp, #12]
	cmp	r12, r2
	blt	.L100
	ldr	r1, [sp, #8]
	b	.L101
.L100:
	ldr	r1, [sp, #12]
.L101:
	ldr	r2, [sp, #8]
	ldr	r3, [sp, #12]
	cmp	r2, r3
	bgt	.L102
	ldr	r0, [sp, #12]
	b	.L103
.L102:
	ldr	r0, [sp, #8]
.L103:
	add	r2, r1, #20
	mov	r3, #0
	cmp	r1, r0
	ite	eq
	moveq	r0, r2
	movne	r0, r3
	ldr	lr, [sp, #4]
	add	sp, sp, #16
	bx	lr
	.cfi_endproc
	.type	asm_test_entry, %function
	.size	asm_test_entry, . - asm_test_entry

	.section .note.GNU-stack,"",%progbits
