# File generated by CompCert 3.17
# Command line: -S -fno-pie -o x86_64/cond_select.s source/cond_select.c
	.text
	.align	16
	.globl asm_test_entry
asm_test_entry:
	.cfi_startproc
	subq	$24, %rsp
	.cfi_adjust_cfa_offset	24
	leaq	32(%rsp), %rax
	movq	%rax, 0(%rsp)
	movl	$20, %eax
	movl	%eax, 8(%rsp)
	movl	$22, %eax
	movl	%eax, 12(%rsp)
	movl	8(%rsp), %edi
	movl	12(%rsp), %edx
	cmpl	%edx, %edi
	jl	.L100
	movl	8(%rsp), %edx
	jmp	.L101
.L100:
	movl	12(%rsp), %edx
.L101:
	movl	8(%rsp), %r9d
	movl	12(%rsp), %esi
	cmpl	%esi, %r9d
	jg	.L102
	movl	12(%rsp), %ecx
	jmp	.L103
.L102:
	movl	8(%rsp), %ecx
.L103:
	leal	20(%edx), %eax
	xorl	%r8d, %r8d
	cmpl	%ecx, %edx
	cmovne	%r8, %rax
	addq	$24, %rsp
	ret
	.cfi_endproc
	.type	asm_test_entry, @function
	.size	asm_test_entry, . - asm_test_entry

	.section .note.GNU-stack,"",%progbits
