# File generated by CompCert 3.17
# Command line: -S -fno-pie -o x86_64/caller.s source/caller.c
	.text
	.align	16
	.globl asm_test_entry
asm_test_entry:
	.cfi_startproc
	subq	$8, %rsp
	.cfi_adjust_cfa_offset	8
	leaq	16(%rsp), %rax
	movq	%rax, 0(%rsp)
	movl	shared_value(%rip), %eax
	leal	22(%eax), %eax
	movl	%eax, shared_value(%rip)
	addq	$8, %rsp
	ret
	.cfi_endproc
	.type	asm_test_entry, @function
	.size	asm_test_entry, . - asm_test_entry

	.section .note.GNU-stack,"",%progbits
