# File generated by CompCert 3.17
# Command line: -S -fno-pie -o riscv64/caller.s source/caller.c
	.option nopic
	.text
	.balign 2
	.globl asm_test_entry
asm_test_entry:
	.cfi_startproc
	mv	x30, x2
	addi	x2, x2, -16
	.cfi_adjust_cfa_offset	16
	sd	x30, 0(x2)
	sd	x1, 8(x2)
	.cfi_rel_offset	x1, 8
	addiw	x10, x0, 20
	call	asm_test_callee
	addiw	x10, x10, 2
	ld	x1, 8(x2)
	addi	x2, x2, 16
	jr	x1
	.cfi_endproc
	.type	asm_test_entry, @function
	.size	asm_test_entry, . - asm_test_entry

	.section .note.GNU-stack,"",%progbits
