# File generated by CompCert 3.17
# Command line: -S -fno-pie -o x86_32/loop.s source/loop.c
	.text
	.align	16
	.globl asm_test_entry
asm_test_entry:
	.cfi_startproc
	subl	$12, %esp
	.cfi_adjust_cfa_offset	12
	leal	16(%esp), %eax
	movl	%eax, 0(%esp)
	movl	$6, %eax
	movl	%eax, 8(%esp)
	xorl	%eax, %eax
	xorl	%edx, %edx
.L100:
	movl	8(%esp), %ecx
	cmpl	%ecx, %edx
	jge	.L101
	leal	7(%eax), %eax
	leal	1(%edx), %edx
	jmp	.L100
.L101:
	addl	$12, %esp
	ret
	.cfi_endproc
	.type	asm_test_entry, @function
	.size	asm_test_entry, . - asm_test_entry

	.section .note.GNU-stack,"",%progbits
