// File generated by CompCert 3.17
// Command line: -S -fno-pie -o aarch64/direct_call.s source/direct_call.c
	.text
	.balign 4
	.globl asm_test_callee
asm_test_callee:
	.cfi_startproc
	mov	x15, sp
	stp	x15, x30, [sp, #-16]!
	.cfi_adjust_cfa_offset	16
	.cfi_rel_offset	x30, 8
	add	w0, w0, w0
	ldr	x30, [sp, #8]
	add	sp, sp, #16
	ret	x30
	.cfi_endproc
	.type	asm_test_callee, @function
	.size	asm_test_callee, . - asm_test_callee
	.text
	.balign 4
	.globl asm_test_entry
asm_test_entry:
	.cfi_startproc
	mov	x15, sp
	stp	x15, x30, [sp, #-16]!
	.cfi_adjust_cfa_offset	16
	.cfi_rel_offset	x30, 8
	movz	w0, #20, lsl #0
	bl	asm_test_callee
	add	w0, w0, #2
	ldr	x30, [sp, #8]
	add	sp, sp, #16
	ret	x30
	.cfi_endproc
	.type	asm_test_entry, @function
	.size	asm_test_entry, . - asm_test_entry

	.section .note.GNU-stack,"",%progbits
